# Use an official Node.js image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install the frontend dependencies
RUN npm install

# Copy the rest of the frontend source code
COPY . .

# Expose the frontend port
EXPOSE 3000

# Start the frontend server using OpenSSL legacy provider
CMD ["sh", "-c", "export NODE_OPTIONS=--openssl-legacy-provider && npm start"]