version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: marc
      POSTGRES_PASSWORD: 560047
      POSTGRES_DB: linotium
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: marc
      DB_PASSWORD: 560047
      DB_NAME: linotium
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app

volumes:
  postgres_data:
